$LOAD_PATH.unshift File.expand_path('../lib/', __FILE__)
require 'active_record'
require 'activerecord/postgresql/citext'
# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

config = {
  :adapter => 'postgresql',
  :template => 'template0',
  :schema_search_path => 'public',
  :database => 'activerecord_postgresql_citext',
  :username => ENV["DB_USERNAME"] || ENV["USER"],
  :password => ENV["DB_PASSWORD"],
  :host => 'localhost',
  :port => ENV["DB_PORT"] || 5433
}
ActiveRecord::Base.establish_connection(config)

RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus
  config.order = 'random'
  config.around(:each) do |spec|
    ActiveRecord::Base.transaction do
      spec.run
      raise ActiveRecord::Rollback
    end
  end
end
